# Logistic Regression (Binary Classification)


Logistic regression is a popular statistical method used for binary classification problems, such as predicting the presence or absence of heart disease based on various predictors. In the context of heart disease prediction, logistic regression models the probability that a given patient has heart disease based on their features.

Thanks for the DataSet: [Dataset Link](https://github.com/rashida048/Datasets/blob/master/Heart.csv)

## Import Necessary Libraries

In [93]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

## Data Preparation

In [94]:
dataframe = pd.read_csv('../data/Heart.csv')
dataframe.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [95]:
dataframe = dataframe.drop(columns=['Unnamed: 0'])
dataframe

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [96]:
dataframe.isna().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [97]:
dataframe = dataframe.dropna()
dataframe

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable,Yes
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes

In [98]:
dataframe.isna().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

In [99]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 297 entries, 0 to 301
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        297 non-null    int64
 1   Sex        297 non-null    int64
 2   ChestPain  297 non-null    object
 3   RestBP     297 non-null    int64
 4   Chol       297 non-null    int64
 5   Fbs        297 non-null    int64
 6   RestECG    297 non-null    int64
 7   MaxHR      297 non-null    int64
 8   ExAng      297 non-null    int64
 9   Oldpeak    297 non-null    float64
 10  Slope      297 non-null    int64
 11  Ca         297 non-null    float64
 12  Thal       297 non-null    object
 13  AHD        297 non-null    object
dtypes: float64(2), int64(9), object(3)
memory usage: 34.8+ KB

In [100]:
dataframe.shape

(297, 14)

## Converting non-numeric data into numeric data

In [101]:
dataframe['ChestPain'] = dataframe['ChestPain'].astype('category')
dataframe['ChestPain'] = dataframe['ChestPain'].cat.codes


dataframe['Thal'] = dataframe['Thal'].astype('category')
dataframe['Thal'] = dataframe['Thal'].cat.codes

dataframe['AHD'] = dataframe['AHD'].astype('category')
dataframe['AHD'] = dataframe['AHD'].cat.codes

dataframe

C:\Users\User\AppData\Local\Temp\ipykernel_8356\2350690969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['ChestPain'] = dataframe['ChestPain'].astype('category')
C:\Users\User\AppData\Local\Temp\ipykernel_8356\2350690969.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['ChestPain'] = dataframe['ChestPain'].cat.codes
C:\Users\User\AppData\Local\Temp\ipykernel_8356\2350690969.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['Thal'] = dataframe['Thal'].astype('category')
C:\Users\User\AppData\Local\Temp\ipykernel_8356\2350690969.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['Thal'] = dataframe['Thal'].cat.codes
C:\Users\User\AppData\Local\Temp\ipykernel_8356\2350690969.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['AHD'] = dataframe['AHD'].astype('category')
C:\Users\User\AppData\Local\Temp\ipykernel_8356\2350690969.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['AHD'] = dataframe['AHD'].cat.codes

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,0
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,1
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,1
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,0,0,140,241,0,0,123,1,0.2,2,0.0,2,1
298,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2,1
299,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2,1
300,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2,1
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1,1

## Assigning the X and y

In [102]:
X = dataframe.drop(columns=['AHD'])
X.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1

In [103]:
y = dataframe['AHD']
y[:5]

0    0
1    1
2    1
3    0
4    0
Name: AHD, dtype: int8

## Splitting the Data (Training Data and test Data)

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

## Data Scaling

In [106]:
scaler = StandardScaler()

In [107]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [108]:
X_train_scaled

array([[-1.74167853, -1.52906121,  0.19776829, ...,  0.62991241,
        -0.72057669, -0.60303463],
       [ 0.60111446, -1.52906121,  2.28092759, ..., -1.01062871,
        -0.72057669, -0.60303463],
       [ 1.60516859, -1.52906121,  2.28092759, ..., -1.01062871,
         1.38777733, -0.60303463],
       ...,
       [ 0.26642974,  0.65399606,  0.19776829, ...,  0.62991241,
         0.33360032,  1.11888352],
       [ 0.48955288,  0.65399606,  2.28092759, ..., -1.01062871,
         1.38777733, -0.60303463],
       [ 1.82829173, -1.52906121,  0.19776829, ..., -1.01062871,
         0.33360032, -0.60303463]])

In [112]:
X_test_scaled[:5]

array([[-1.07230911, -1.52906121,  1.23934794, -1.12522849, -1.69153882,
        -0.43698372, -1.04980046, -0.4521183 , -0.73413966, -0.91504143,
         0.62991241, -0.72057669, -0.60303463],
       [-0.29137811,  0.65399606, -0.84381136, -1.12522849, -0.35299224,
        -0.43698372, -1.04980046,  0.4968933 , -0.73413966, -0.91504143,
        -1.01062871,  0.33360032, -0.60303463],
       [-0.06825497, -1.52906121,  0.19776829,  0.15260911,  1.06204272,
         2.28841476, -1.04980046,  0.92826221, -0.73413966, -0.91504143,
        -1.01062871, -0.72057669, -0.60303463],
       [ 1.71673016,  0.65399606, -0.84381136, -0.12518167,  1.40624041,
        -0.43698372,  0.96479637, -1.70308815, -0.73413966,  1.2007129 ,
         0.62991241,  2.44195435, -0.60303463],
       [ 0.15486817,  0.65399606,  1.23934794, -0.68076324, -0.23825968,
        -0.43698372, -1.04980046,  1.27335734, -0.73413966, -0.20978999,
        -1.01062871, -0.72057669, -0.60303463]])